### ISSUE TITLE
Compilation error on Ubuntu 15.04

### ISSUE THREAD

**Issue by SummerStorm** [giacomodabisias/libfreenect2pclgrabber#2]
I got the following error when trying compile on Ubuntu 15.04:

     In file included from /home/user/code/libfreenect2pclgrabber/test.cpp:15:0:
     /home/user/code/libfreenect2pclgrabber/Kinect2Grabber.hpp: In constructor ‘Kinect2Grabber::Kinect2Grabber<PointT>::Kinect2Grabber(std::string, std::string, int, const Size&, double)’:
     /home/user/code/libfreenect2pclgrabber/Kinect2Grabber.hpp:114:12: warning: there are no arguments to ‘glfwInit’ that depend on a template parameter, so a declaration of ‘glfwInit’ must be available [-fpermissive]
    glfwInit();
            ^
     /home/user/code/libfreenect2pclgrabber/Kinect2Grabber.hpp: In constructor ‘Kinect2Grabber::Kinect2Grabber<PointT>::Kinect2Grabber(std::string, std::string, std::string)’:
     /home/user/code/libfreenect2pclgrabber/Kinect2Grabber.hpp:140:12: warning: there are no arguments to ‘glfwInit’ that depend on a template parameter, so a declaration of ‘glfwInit’ must be available [-fpermissive]
    glfwInit();
            ^
     /home/user/code/libfreenect2pclgrabber/Kinect2Grabber.hpp: In instantiation of ‘Kinect2Grabber::Kinect2Grabber<PointT>::Kinect2Grabber(std::string, std::string, std::string) [with PointT = pcl::PointXYZRGB; std::string = std::basic_string<char>]’:
     /home/user/code/libfreenect2pclgrabber/test.cpp:25:174:   required from here
     /home/user/code/libfreenect2pclgrabber/Kinect2Grabber.hpp:140:12: error: ‘glfwInit’ was not declared in this scope
    CMakeFiles/Kinect2Grabber.dir/build.make:57: recipe for target 'CMakeFiles/Kinect2Grabber.dir/test.cpp.o' failed

Any help would be much appreciated.

Am I perhaps using the wrong GLFW library version?

**Comment by SummerStorm** [comment]
Adding `#include <GLFW/glfw3.h>` to `Kinect2Grabber.hpp` solved the issue for me.
